---

#
# The task will block until the given environment state 
# as found in the internal objectstore is available
#

platform: linux

image_resource:
  type: docker-image
  source:
    repository: appbricks/automation-tools

run:
  path: /bin/bash
  args:
  - -c
  - |
    mc config host add auto $AUTOS3_URL $AUTOS3_ACCESS_KEY $AUTOS3_SECRET_KEY

    start_time=$(date +%s)
    state=""

    while [[ true ]]; do
      state=$(mc find auto/pcf/$WAIT_FOR_STATE --name "$WAIT_FOR_STATE-*" --exec "echo {}" 2>/dev/null)
      if [[ -n $state ]]; then 
        break
      fi

      sleep 10

      time_now=$(date +%s)
      ss=$(($time_now-$start_time))
      h=$(($ss/3600))
      m=$(($ss/60-$h*60))
      s=$(($ss-$m*60-$h*3600))

      echo -e -n "Waiting $(printf "%02d" $h):$(printf "%02d" $m):$(printf "%02d" $s) hours for environment state '$WAIT_FOR_STATE'.\r"
    done
    echo

params:
  WAIT_FOR_STATE:
  AUTOS3_URL:
  AUTOS3_ACCESS_KEY:
  AUTOS3_SECRET_KEY:
